Add service to crud a tag
OngDev/blog-api pull request #65
Opened 2020-09-11 07:59 UTC by nganvn

2020-09-14 09:24 UTC, MiloNguyen95 requested changes

2020-09-14 09:24 UTC, MiloNguyen95 commented on src/main/kotlin/com/ongdev/blog/api/services/impl/TagServiceImpl.kt
> +    override fun getAllTagByLink(link: String, pageable: Pageable): TagListResponse {
Sao mình không làm kiểu TagListResponse là Page<TagResponse>, khi đó mình chỉ cần map qua thôi đúng ko hè?
Với lại, nếu chỗ này handle như này, thì em check những chỗ khác làm việc với Page xem nó làm việc như nào, nếu khác thì sửa hết lại cho nó consistent

2020-09-14 09:24 UTC, MiloNguyen95 commented on src/test/kotlin/services/TagServiceUnitTest.kt
> +    fun testTagService() {
Em tách cái test này ra từng function khác nhau nha. Đừng gộp như này.

2020-09-14 09:24 UTC, MiloNguyen95 commented on src/test/kotlin/services/TagServiceUnitTest.kt
> +    fun testTagService() {
Và nhớ test luôn cả bad cases

2020-09-14 09:24 UTC, MiloNguyen95 commented on src/main/kotlin/com/ongdev/blog/api/models/repositories/TagRepository.kt
> +    fun findAllByLink(link: String, pageable: Pageable): Page<Tag>
Mình có find by name ko e

2020-09-14 09:24 UTC, MiloNguyen95 commented on src/main/kotlin/com/ongdev/blog/api/models/dtos/responses/TagListResponse.kt
> +        val result: List<TagResponse>,
Sao ko dùng kiểu result: Page<TagResponse> ?

2020-09-14 09:24 UTC, MiloNguyen95 commented on src/main/kotlin/com/ongdev/blog/api/models/Mapper.kt
> +var appUtils: AppUtils = AppUtils()
hmm, cái này a nghĩ là private val chứ hè, var là editable rồi

2020-09-17 01:17 UTC, nganvn commented on src/main/kotlin/com/ongdev/blog/api/models/Mapper.kt
> +var appUtils: AppUtils = AppUtils()
dạ, :D 
à mà anh ơi, bữa làm cái task "Remove Vietnamese accents", em không để ý. 
lẽ ra phải đưa cái fun trong AppUtils vào trong companion object để gọi luôn chứ không cần phải tạo instance để gọi chứ anh hè, anh amend vào master được không anh?

2020-09-17 01:40 UTC, nganvn commented on src/main/kotlin/com/ongdev/blog/api/models/dtos/responses/TagListResponse.kt
> +        val result: List<TagResponse>,
Em nghĩ Page nó convert sang Json nó có nhiều cái thừa
Với lại convert Page<Tag> sang Page<Response> rườm rà nữa

2020-09-17 01:42 UTC, nganvn commented on src/main/kotlin/com/ongdev/blog/api/models/repositories/TagRepository.kt
> +    fun findAllByLink(link: String, pageable: Pageable): Page<Tag>
oh, có anh, để em tạo thêm task

2020-09-28 03:50 UTC, MiloNguyen95 commented on src/main/kotlin/com/ongdev/blog/api/models/Mapper.kt
> +var appUtils: AppUtils = AppUtils()
Cái đó em tạo 1 ticket bug rồi làm riêng ra e

2020-09-28 03:51 UTC, MiloNguyen95 commented on src/main/kotlin/com/ongdev/blog/api/models/dtos/responses/TagListResponse.kt
> +        val result: List<TagResponse>,
uh ok, vì cái tag này cũng ko có phân trang gì, nên mình có thể consider là không làm phân trang cho nó luôn

2020-10-30 14:43 UTC, OngDevTech approved these changes

2020-10-30 14:44 UTC, merged