Feature/get categories by link
OngDev/blog-api pull request #77
Opened 2021-01-04 06:02 UTC by vkhanhqui

2021-01-31 05:15 UTC, MiloNguyen95 commented on src/main/kotlin/com/ongdev/blog/api/controllers/CategoryController.kt
> +    @GetMapping("link/{link}")
Chỗ này không cần /link đâu nha, em để nó là ? link = ... là đc. Nghĩa là request param á. ví dụ:
localhost:3333/category?link=...

2021-01-31 05:16 UTC, MiloNguyen95 requested changes
Check lại url

2021-01-31 12:13 UTC, vkhanhqui commented on src/main/kotlin/com/ongdev/blog/api/controllers/CategoryController.kt
> +    @GetMapping("link/{link}")
> Chỗ này không cần /link đâu nha, em để nó là ? link = ... là đc. Nghĩa là request param á. ví dụ:
> localhost:3333/category?link=...

Để như vậy nó bị trùng url, còn cách nào nữa không anh

2021-02-01 08:51 UTC, MiloNguyen95 commented on src/main/kotlin/com/ongdev/blog/api/controllers/CategoryController.kt
> +    @GetMapping("link/{link}")
hmm, v để v cũng đc

2021-02-01 08:52 UTC, merged